# Generated by Django 3.0.3 on 2020-02-17 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(default=None, max_length=255, null=True)),
                ('text', models.CharField(default=None, max_length=255, null=True)),
                ('last_update', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=None, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'note',
                'verbose_name_plural': 'note',
            },
        ),
    ]
